apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)

    - name: npminstall
      taskRef:
        name: npm
      runAfter:
        - name: clone-repository
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: tests
      taskRef:
        name: jasmine
      runAfter:
        - name: npminstall
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build
      taskRef:
        name: buildah
      runAfter:
        - name: tests
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.image-name)
